# Generated by Django 4.2.7 on 2024-07-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date_played',
        ),
        migrations.RemoveField(
            model_name='game',
            name='score_left',
        ),
        migrations.RemoveField(
            model_name='game',
            name='score_right',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
