version: "3.9"

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Core/Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - django-files:/Django
    depends_on:
      - db
    networks:
      - transcendence
    restart: on-failure

  db:
    image: postgres
    container_name: db
    build:
      context: .
      dockerfile: Database/Dockerfile
    volumes:
      - db-files:/var/lib/postgresql/data
    networks:
      - transcendence
    ports:
      - "5432:5432"
    env_file: .env

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  django-files:
    name: django-files
    driver: local
    driver_opts:
      device: /Users/arobu/projects/workdir/transcendence/Core/data
      o: bind
      type: none

  db-files:
    name: db-files
    driver: local
    driver_opts:
      device: /Users/arobu/projects/workdir/transcendence/Database/data
      o: bind
      type: none
