version: "3.9"
services:
  server:
    environment:
      - DJANGO_SETTINGS_MODULE=transcendence.settings
    container_name: server
    build:
      context: ./transcendence
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "443:443"
    volumes:
      - django-files:/server
    networks:
      - transcendence
    restart: unless-stopped
  db:
    container_name: db
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db-files:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: unless-stopped
networks:
  transcendence:
    driver: bridge
volumes:
  django-files:
  db-files: