# Generated by Django 4.2.7 on 2024-05-19 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twofa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chosen_2fa_method',
            field=models.CharField(choices=[('qr', 'QR Code'), ('sms', 'SMS'), ('email', 'Email')], default='qr', max_length=50),
        ),
        migrations.CreateModel(
            name='TwilioSMSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('key', models.CharField(max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
