# Generated by Django 4.2.7 on 2024-05-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0003_emailotpdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotpdevice',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='twiliosmsdevice',
            name='key',
            field=models.CharField(max_length=100),
        ),
    ]
