# Generated by Django 4.2.7 on 2024-05-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0006_alter_userprofile_chosen_2fa_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chosen_2fa_method',
            field=models.CharField(blank=True, choices=[('qr', 'QR Code'), ('sms', 'SMS'), ('email', 'Email')], default=None, max_length=50, null=True),
        ),
    ]
