# Generated by Django 4.2.7 on 2024-05-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0007_alter_userprofile_chosen_2fa_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotpdevice',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
