# Generated by Django 4.2.7 on 2024-05-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0009_customtotpdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTOTPDevice',
        ),
    ]
