version: "3.9"

services:
  django:
    container_name: DjangoBackendService
    build: ./Core/WebService
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - django-files:/Django

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  django-files:
    name: django-files