FROM postgres:16-bullseye

#COPY ./Database/init-user-db.sh /docker-entrypoint-initdb.d/
#RUN echo "POSTGRES_DB: $POSTGRES_DB"
#RUN echo "POSTGRES_USER: $POSTGRES_USER"
#RUN echo "POSTGRE_PASSWORD: $POSTGRES_PASSWORD"