# Generated by Django 4.2.7 on 2024-02-29 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupconversation',
            name='participants',
            field=models.ManyToManyField(related_name='group_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
