# Generated by Django 4.2.7 on 2024-02-02 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobby', '0002_alter_rooms_player_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='rooms',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
