# Generated by Django 4.2.7 on 2024-02-05 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobby', '0003_remove_rooms_assigned_users_rooms_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
