# Generated by Django 4.2.7 on 2024-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_alter_rooms_assigned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='type',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
