# Generated by Django 4.2.8 on 2023-12-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
