# Generated by Django 4.2.7 on 2024-01-17 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponglobby',
            name='player_two',
        ),
        migrations.AlterField(
            model_name='ponglobby',
            name='lobby_id',
            field=models.UUIDField(default=uuid.UUID('ebefcf84-c25e-4e1d-bbed-e4bf1bfbb735'), editable=False, unique=True, verbose_name=uuid.uuid4),
        ),
    ]
