# Generated by Django 4.2.7 on 2024-01-17 17:07

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_remove_ponglobby_player_two_alter_ponglobby_lobby_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponglobby',
            name='player_one',
        ),
        migrations.AddField(
            model_name='ponglobby',
            name='lobby_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ponglobby',
            name='player_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ponglobby',
            name='users',
            field=models.ManyToManyField(related_name='lobbies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ponglobby',
            name='lobby_id',
            field=models.UUIDField(default=uuid.UUID('7e23512f-9d48-4fd7-b537-2855f5659b51'), editable=False, unique=True, verbose_name=uuid.uuid4),
        ),
    ]
