# Generated by Django 4.2.7 on 2024-01-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bullshit',
            field=models.CharField(),
        ),
    ]
