# Generated by Django 4.2.7 on 2024-01-17 17:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_remove_ponglobby_player_one_ponglobby_lobby_full_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponglobby',
            name='lobby_id',
            field=models.UUIDField(default=uuid.UUID('d0e7dbe4-145a-45e2-9b44-6cf5f875cf60'), editable=False, unique=True, verbose_name=uuid.uuid4),
        ),
    ]
