# Generated by Django 4.2.7 on 2024-01-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_alter_customuser_bullshit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bullshit',
            new_name='customfield',
        ),
    ]
