# Generated by Django 4.2.7 on 2024-01-18 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_alter_ponglobby_lobby_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponglobby',
            name='lobby_id',
            field=models.UUIDField(default=uuid.UUID('ddbf768a-73f1-4a5e-a106-9264f070db41'), editable=False, unique=True, verbose_name=uuid.uuid4),
        ),
    ]
