# Generated by Django 4.2.7 on 2024-01-19 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_alter_ponglobby_lobby_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponglobby',
            name='lobby_id',
            field=models.UUIDField(default=uuid.UUID('8f965bd7-9d7f-4912-90a4-e703ececf359'), editable=False, unique=True, verbose_name=uuid.uuid4),
        ),
    ]
