# Generated by Django 4.2.7 on 2024-01-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_rename_customfield_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
    ]
