# Generated by Django 4.2.7 on 2024-01-19 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_alter_ponglobby_lobby_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponglobby',
            name='lobby_id',
            field=models.UUIDField(default=uuid.UUID('729a541b-1a8b-424c-9583-2b0ecb85540c'), editable=False, unique=True, verbose_name=uuid.uuid4),
        ),
    ]
