# Generated by Django 4.2.7 on 2024-01-19 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_alter_ponglobby_lobby_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponglobby',
            name='lobby_id',
            field=models.UUIDField(default=uuid.UUID('c8373fa7-d05a-42d8-b705-2b639075333a'), editable=False, unique=True, verbose_name=uuid.uuid4),
        ),
    ]
