# Generated by Django 4.2.7 on 2024-01-19 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0009_alter_ponglobby_lobby_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponglobby',
            name='lobby_full',
        ),
        migrations.RemoveField(
            model_name='ponglobby',
            name='lobby_id',
        ),
        migrations.RemoveField(
            model_name='ponglobby',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ponglobby',
            name='player_count',
        ),
        migrations.RemoveField(
            model_name='ponglobby',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ponglobby',
            name='users',
        ),
        migrations.AlterModelTable(
            name='ponglobby',
            table='pong_lobby',
        ),
        migrations.CreateModel(
            name='LobbyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('player_count', models.IntegerField(default=0)),
                ('is_room_full', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(related_name='room_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.AddField(
            model_name='ponglobby',
            name='rooms',
            field=models.ManyToManyField(to='Frontend.lobbyroom'),
        ),
    ]
