# Generated by Django 4.2.7 on 2024-01-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_remove_ponglobby_lobby_full_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbyroom',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
