# Generated by Django 4.2.7 on 2024-01-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_alter_lobbyroom_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ponglobby',
            table='lobby_rooms',
        ),
    ]
