# Generated by Django 4.2.7 on 2024-01-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_alter_ponglobby_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbyroom',
            name='users',
        ),
    ]
