# Generated by Django 4.2.7 on 2024-01-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='frontend/profile_pics/'),
        ),
    ]
