# Generated by Django 4.2.7 on 2024-01-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='nickname',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
