# Generated by Django 4.2.7 on 2024-05-18 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
