# Generated by Django 4.2.7 on 2024-05-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
