# Generated by Django 4.2.7 on 2024-05-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountuser_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='third_party_auth',
            field=models.BooleanField(default=False),
        ),
    ]
